const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { test } = require('node:test');
const { publishLinks, refreshRepository } = require('../blog-vk-collector');

test('publishes only the VK map and refuses unrelated dirty files or a different production remote', t => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'blog-vk-publisher-'));
    t.after(() => fs.rmSync(root, { recursive: true, force: true }));
    const repository = path.join(root, 'repo');
    const remote = path.join(root, 'remote.git');
    fs.mkdirSync(repository);
    const git = (...args) => execFileSync('git', args, { cwd: repository, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
    git('init', '--initial-branch=main');
    git('config', 'user.name', 'Test fixture');
    git('config', 'user.email', 'fixture@example.invalid');
    git('init', '--bare', '--initial-branch=main', remote);
    fs.mkdirSync(path.join(repository, 'data'));
    const mapFile = path.join(repository, 'data/blog-vk-links.json');
    fs.writeFileSync(mapFile, '{}\n');
    fs.writeFileSync(path.join(repository, 'README.md'), 'Unrelated baseline\n');
    git('add', 'data/blog-vk-links.json', 'README.md');
    git('commit', '-m', 'fixture');
    git('remote', 'add', 'origin', remote);
    git('push', '-u', 'origin', 'main');
    const baseline = git('rev-parse', 'HEAD');
    assert.throws(() => refreshRepository(repository), /VK_COLLECTOR_REPOSITORY_INVALID/);
    assert.throws(() => publishLinks(repository), /VK_COLLECTOR_REPOSITORY_INVALID/);
    fs.writeFileSync(mapFile, '{"363":"https://vk.ru/im/channels/-232523704?cmid=501"}\n');
    publishLinks(repository, remote);
    assert.equal(git('diff', '--name-only', baseline, 'HEAD'), 'data/blog-vk-links.json');
    const published = git('--git-dir=' + remote, 'rev-parse', 'main');
    assert.equal(published, git('rev-parse', 'HEAD'));
    publishLinks(repository, remote);
    assert.equal(git('rev-parse', 'HEAD'), published);
    fs.writeFileSync(path.join(repository, 'README.md'), 'User change\n');
    fs.writeFileSync(mapFile, '{"364":"another-link"}\n');
    assert.throws(() => publishLinks(repository, remote), /VK_COLLECTOR_WORKTREE_DIRTY/);
    assert.equal(git('rev-parse', 'HEAD'), published);
    assert.equal(git('--git-dir=' + remote, 'rev-parse', 'main'), published);
    assert.equal(fs.readFileSync(path.join(repository, 'README.md'), 'utf8'), 'User change\n');
});
